package jzy.taining.plugins.jspark.features.templates.templates

import jzy.taining.plugins.jspark.features.templates.data.TemplateValues

fun jsparkActivity(templateValues: TemplateValues) =
    """
package ${templateValues.packageName}

import com.heytap.sporthealth.blib.basic.ui.BasicActivity
import ${templateValues.fullViewBeanName}
import ${templateValues.fullViewModelName}
import ${templateValues.applicationId}.R
import android.os.Bundle

/**
 *  generated by jspark
 */
class ${templateValues.activityName} : BasicActivity<${templateValues.viewModelName}, ${templateValues.viewBeanName}>() {
    
    override fun setContentLayout() = R.layout.${templateValues.activityLayoutName}
    
    override fun initView() {
        TODO("这里查找所有控件")
    }
    
    override fun provideViewModel() = ${templateValues.viewModelName}::class.java
    
    override fun showSucceed(result: ${templateValues.viewBeanName}?) {
        super.showSucceed(result)
        TODO("业务逻辑加载到数据之后执行，使用result填充界面控件")
    }
    
}
    """