package jzy.taining.plugins.jspark.features.templates.templates

import jzy.taining.plugins.jspark.features.templates.data.TemplateValues

fun jsparkRecvActivity(templateValues: TemplateValues) =
    """
package ${templateValues.packageName}

import com.heytap.sporthealth.blib.basic.ui.BasicRecvActivity
import ${templateValues.fullViewBeanName}
import ${templateValues.fullViewModelName}
import ${templateValues.applicationId}.R
import android.os.Bundle

/**
 *  generated by jspark
 */
class ${templateValues.activityName} : BasicRecvActivity<${templateValues.viewModelName}, ${templateValues.viewBeanName}>() {
    
    override fun provideViewModel() = ${templateValues.viewModelName}::class.java
    
}
    """