package jzy.taining.plugins.jspark.features.templates.templates

import jzy.taining.plugins.jspark.features.templates.data.TemplateValues

fun jsparkRecvViewmodel(templateValues: TemplateValues) =
    """
package ${templateValues.packageName}

import android.app.Application
import io.reactivex.disposables.Disposable
import com.heytap.sporthealth.blib.basic.BasicRecvLoadMoreViewModel
import first.lunar.yun.adapter.vb.JViewBean
import ${templateValues.fullViewBeanName}

/**
 *  generated by jspark
 */
class ${templateValues.viewModelName}(application: Application?, param: Any?): BasicRecvLoadMoreViewModel<${templateValues.viewBeanName}>(application, param) {

    override fun onPullData(param: Any?): Disposable {
        TODO("业务逻辑请求数据")
        return super.onPullData(param)
    }
    
}
    """